version: '2'
services:
    microservicegatewaystudent-app:
        image: microservicegatewaystudent
        external_links:
            - microservicegatewaystudent-mysql:mysql
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/microservicegatewaystudent?useUnicode=true&characterEncoding=utf8&useSSL=false
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=cassandra
            - JHIPSTER_SLEEP=30
        ports:
            - 8080:8080
    microservicegatewaystudent-mysql:
        container_name: microservicegatewaystudent-mysql
        image: mysql:5.7.13
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=microservicegatewaystudent
        command: mysqld --lower_case_table_names=1 --skip-ssl
    
    microservicesstudent-app:
        image: microservicesstudent
        external_links:
            - microservicesstudent-mysql:mysql
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/microservicesstudent?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10
    microservicesstudent-mysql:
        container_name: microservicesstudent-mysql
        image: mysql:5.7.13
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=microservicesstudent
        command: mysqld --lower_case_table_names=1 --skip-ssl
    
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry


